### ISSUE TITLE
Does this take screenshots?

### ISSUE THREAD

**Issue by OKNoah** [InternetExplorer/modern.IE-static-code-scan#76]
Does this take screenshots of the web page as IE would see them?

From http://modern.ie:

	Homepage:

	Browser Screenshots
	Get screenshots of how your site looks across nine common browsers and devices. (links to https://www.modern.ie/en-us/screenshots)

	Screenshots page:
	 
	Get screenshots of your site. 
	Enter a webpage URL here:
	Open source version available on GitHub. Download here (links to this github repo)

But after using the app to "scan" the page, I don't see screenshots, just a prompt to send info to http://modern.ie.

WTF?

**Comment by molant** [comment]
This is the static scan tool. We are using browser stack to take screenshots of the website for the [browser screenshots](https://www.modern.ie/en-us/screenshots)

**Comment by OKNoah** [comment]
I see you closed this but the copy on the website is the same.

**Comment by molant** [comment]
Can you please point me to the page where it says the static code scan takes screenshots so I can talk to the right people?
Thanks!

-----Original Message-----

**Comment by OKNoah** [comment]
@molant Same one you linked to above: https://www.modern.ie/en-us/screenshots

![image](http://i.imgur.com/TJEvptn.png)

Spartan browser use case right here I guess.
