### ISSUE TITLE
Error when scanning

### ISSUE THREAD

**Issue by MikeFromSwe** [InternetExplorer/modern.IE-static-code-scan#82]
Hi
I downloaded the windows installer node (v0.12.0) and installed it (Running Win8.1)
Started 
node js (command prompt) and entered npm install 
There were som errors, which I cant reproduce.
And then from the same console entered "node app.js"
Surfed to http:\\localhost:1337
Entered a local website and hit enter:
First i get a prompt saying : "Failed: 0"
In the Node command prompt it says:
*Server started on port 1337
To scan a private url go to http://localhost:1337/ and follow the instructions
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (C:\temp\modern.IE-static-code-scan-master\node_modules\req
uest\request.js:583:30)
    at Request.end (C:\temp\modern.IE-static-code-scan-master\node_modules\reque
st\request.js:1237:28)
    at C:\temp\modern.IE-static-code-scan-master\node_modules\request\request.js
:413:12
    at process._tickCallback (node.js:355:11)*

**Comment by molant** [comment]
OK, I've tried with 0.10.36 and it is working. The problems when doing `npm install` are probably because of jsdom (at least I saw some errors in that package right now). I don't think we are using it so I should probably remove that dependency. I'll test with 0.12.x see what happens

**Comment by molant** [comment]
Yup, looks like an issue with 0.12.0
Can you downgrade to 0.10.36 in the meantime?

**Comment by molant** [comment]
Closing and tracking via #83
