### ISSUE TITLE
Why I am getting this error? 

### ISSUE THREAD

**Issue by sarwarcse** [InternetExplorer/modern.IE-static-code-scan#84]
Anyone please advice me why am getting this error?
-------------------------------------------------------------------------------------------------------------
E:\modern\modern.IE-static-code-scan-master>node app.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\mordern\modern.IE-static-code-scan-master\app.js:23:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by dmethvin** [comment]
Did you `npm install`?

**Comment by sarwarcse** [comment]
I am using windows 8.1 and installed node.js

**Comment by dmethvin** [comment]
https://github.com/InternetExplorer/modern.IE-static-code-scan#installation-and-configuration

**Comment by sarwarcse** [comment]
I am getting this error when i run npm install, any suggestion?
------------------
 configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\mordern\modern.IE-static-code-scan-master\node_modules\jsdom\nod
e_modules\contextify
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing contextify@0.1.13
npm ERR! registry error parsing json

**Comment by molant** [comment]
Looks like you've past this issue and now you are seeing the issue with node 0.12.
I'm closing this now.
