### ISSUE TITLE
'offline' not working within local

### ISSUE THREAD

**Issue by DisposableHero** [InternetExplorer/modern.IE-static-code-scan#87]
Hello,
I'm trying to get the modern.ie code project to work 'offline' within my local environment. I setup a local URL as http://localhost:1339/index.html. I've setup a test page simply as http://localhost:1339/test1/test1.html. I've set the /lib directory as the root folder within IIS and the other directories as Virtual Directories (may not be necessary).

- master branch: I get 500 error on scan report result on the modern.ie site.
- vNext branch: I get empty scan report results on modern.ie site.
- I've tried in IE9 and IE11.
- I've tried changing the HTTP to HTTPS in the form post

Any help would be appreciated. Thanks.

**Comment by molant** [comment]
Are you using any type of authentication with IIS (ntlm for example)?

Is the error 500 the result of scanning your website or does it actually have a problem?
If you try scanning another website (www.bing.com for example), does it work?
Have you tried using http://127.0.0.1/index.html?


-----Original Message-----

**Comment by DisposableHero** [comment]
Thanks for response molant. I'm using Windows 7 Enterprise with IIS 6 with Anonymous Authentication enabled. For 'www.bing.com' I get error 'Failed: 0' alert along with Error: "name" and "value" for setHeader(). Same errors with any local static test pages such as http://localhost:1339/test1/test1.html.

**Comment by molant** [comment]
You are using node 0.12. This is a known issue (see other issues). The work around for now is to use 0.10.36.

Thanks!

-----Original Message-----

**Comment by DisposableHero** [comment]
Yes, that fixed it. Thanks!

**Comment by dharmeshqk** [comment]
I am not able to scan an application, node has been successfully installed. later I installed npm. It still shows me 500 just after entering url usename and password
PFA Screen shot of RESULT shown on cmd

**Comment by dharmeshqk** [comment]
Sorry could not send screen shot due to security issue. 
{ [Error: connect TIMEDOUT]

**Comment by dharmeshqk** [comment]
Failded: 500
{ "cause":{"code":"ETIMEDOUT", errno:ETIMEDOUT, syscall:connect}
isOpertionable:true,"code":ETIMEDOUT,errno:ETIMEDOUT,syscall:connect}

**Comment by molant** [comment]
@dharmeshqk does the website you are trying to scan require authentication like NTLM? That could be the issue

**Comment by dharmeshqk** [comment]
@molten: We will check with Server support team  whether we are using any authentication like NTLM or any other. By time, can you guide what is work around for that. Thanks!!
